language: cpp
os: linux
compiler: gcc
sudo: required
dist: trusty

addons:
  apt:
    packages:
      - cmake
      - g++-4.8
        # OpenGL related
      - libgl1-mesa-dev
      - mesa-utils
      - libgl1-mesa-glx 
  coverity_scan:
    project:
      name: "mm-project/qt_painter"
      description: "Coverity build submitted via Travis CI"
    notification_email: baghi.blbul@gmail.com
    build_command_prepend: "cov-configure --comptype gcc --compiler gcc-4.8 --template"
    build_command:   "make -j2 VERBOSE=1"
    branch_pattern: coverity_scan
