language: cpp
os: linux
compiler: gcc
dist: trusty
sudo: required


addons:
  coverity_scan:
    project:
      name: mm-project/qt_painter
    build_command_prepend: "cmake"
    build_command: "make"
    branch_pattern: coverity_scan
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang

compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get upgrade && sudo apt-get update && sudo apt-get install -y git less wget cmake xvfb build-essential qt5-default python3 python3-pip curl; sudo pip3 install requests
  - cmake .

script:
  - make
