language: cpp
os: linux
compiler: gcc
dist: Bionic
sudo: required


addons:
  coverity_scan:
    project:
      name: mm-project/qt_painter
    build_command_prepend: "cmake"
    build_command: "make"
    branch_pattern: coverity_scan
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - clang

compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get --allow-unauthenticated install -y git less wget cmake xvfb build-essential qt5-default python3 python3-pip curl
  - cmake .

script:
  - make
