language: cpp
os: linux
compiler: gcc
sudo: required
dist: trusty


addons:
  coverity_scan:
    project:
      name: mm-project/qt_painter
    build_command_prepend: "cmake"
    build_command: "make"
    branch_pattern: coverity_scan
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang

compiler:
  - gcc
  - clang

before_script:
  - cmake .

script:
  - make
