version: 1.1.{build}
os: Visual Studio 2017

environment:
  matrix:
  - ARCH: amd64
  - ARCH: x86

install:
- cmake -G "Visual Studio 15 2017" .

build_script:
- cmake -G "Visual Studio 15 2017" .
- cmake --build .
