version: 2
jobs:
  build:
    docker:
        - image: ubuntu:xenial
    steps:
      - checkout
      - run:
          name: deps
          command: apt-get update && apt-get install -y git less wget cmake xvfb build-essential qt5-default python3 python3-pip curl; pip3 install requests; pip3 install json;  pip3 install base64
      - run:
          name: compile
          command: export TERM=xterm; cmake CMakeLists.txt; make
      - run:
          name: regressions
          command: export CI_CHECK=1; export TERM=xterm;  xvfb-run ./sqa/bin/runRegTests.sh
      - store_artifacts:
          path: /root/project/sqa/
