version: 2
jobs:
  build:
    docker:
        - image: hopar/qtpainter:0.0.1
    steps:
      - checkout
      - run:
          name: compile
          command: export TERM=xterm; cmake CMakeLists.txt; make
      - run:
          name: compile_ut
          command: export TERM=xterm; ./etc/bsys/bin/makeUnitTests.sh
      - run:
          name: testing_unit
          command: export CI_BUILD="CCI_UNIT_TEST$CIRCLE_BUILD_NUM"; export CI_CHECK=1; export TERM=xterm;  xvfb-run ./qa/bin/runUnitTests.sh
      - run:
          name: testing_integrations
          command: export CI_BUILD="CCI_INTG_TEST$CIRCLE_BUILD_NUM"; export CI_CHECK=1; export TERM=xterm;  xvfb-run ./qa/bin/runRegTests.sh
      - store_artifacts:
          path: /root/project/qa/
