version: 2
jobs:
  build:
    docker:
        - image: ubuntu:xenial
    steps:
      - checkout
      - run:
          name: deps
          command: apt-get update && apt-get install -y git less wget cmake xvfb build-essential qt5-default python3 python3-pip curl; pip3 install requests
      - run:
          name: compile
          command: export TERM=xterm; cmake CMakeLists.txt; make
      - run:
          name: compile_ut
          command: export TERM=xterm; cd src/commands/test; make
      - run:
          name: testing_unit
          command: export CI_BUILD="CCI_UNIT_TEST$CIRCLE_BUILD_NUM"; export CI_CHECK=1; export TERM=xterm;  xvfb-run ./sqa/bin/runUnitTests.sh
      - run:
          name: testing_integrations
          command: export CI_BUILD="CCI_INTG_TEST$CIRCLE_BUILD_NUM"; export CI_CHECK=1; export TERM=xterm;  xvfb-run ./sqa/bin/runRegTests.sh
      - store_artifacts:
          path: /root/project/sqa/
