jobs:
  build:
    docker:
        - image: hopar/qtpainter:dev-latest
    steps:
      - checkout
      - run:
          name: compile
          command: export TERM=xterm; cmake CMakeLists.txt; make -j8
      - run:
          name: compile_ut
          command: export TERM=xterm; ./etc/bsys/bin/makeUnitTests.sh
      - run:
          name: testing_unit
          command: export CI_BUILD="CCI_UNIT_TEST$CIRCLE_BUILD_NUM"; export CI_CHECK=1; export TERM=xterm;  xvfb-run ./sqa/bin/runUnitTests.sh
      - run:
          name: testing_integrations
          command: export CI_BUILD="CCI_INTG_TEST$CIRCLE_BUILD_NUM"; export CI_CHECK=1; export TERM=xterm; export PAINTER_QA_XVFB=1; ./sqa/bin/runTestsParallel.sh
      - store_artifacts:
          path: /root/project/artifacts
  docker-build-push:
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      - run:
          name: Docker_build
          command: docker build -t hopar/qtpainter:dev-latest -f ./etc/bsys/Dockerfile .
      - run:
          name: Docker_login_and_push
          command: | 
            echo "dckr_pat_jtbg6h0lWaqcxnDKWPeBM09BNlQ" | docker login --username hopar --password-stdin
            docker push hopar/qtpainter:dev-latest

workflows:
  version: 2
  build-app:
    jobs:
      - build
  docker-build-and-push:
    jobs:
      - docker-build-push:
          filters:
            branches:
              only:
                - issue-188/Add-circeci-workflow-for-docker-build-push
      - build:
          requires:
            - docker-build-push
          filters:
            branches:
              only:
                - issue-188/Add-circeci-workflow-for-docker-build-push

#build-and-test:
  #  jobs:
  #    - build
