FROM ubuntu:22.04
RUN apt-get upgrade && apt-get update && apt-get install -y git less wget cmake xvfb build-essential qtbase5-dev qtbase5-dev-tools ffmpeg python3 python3-pip curl; pip3 install requests
