/* This file was generated by syncqt. */
#ifndef QT_QTUIPLUGIN_VERSION_H
#define QT_QTUIPLUGIN_VERSION_H

#define QTUIPLUGIN_VERSION_STR "5.7.1"

#define QTUIPLUGIN_VERSION 0x050701

#endif // QT_QTUIPLUGIN_VERSION_H
